#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Jan 12 22:31:28 CET 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=8
shaderPack=Stracciatella Shaders v1.6.4 by DrDesten.zip
enableShaders=true
