#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Dec 01 14:37:09 CET 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=\u00A7lLITE shaders 4.6.3.zip
enableShaders=true
