
[light_sources]
	entities = true
	self = true
	block_entities = true
	water_sensitive_check = true

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				player = true
				bee = true
				item = true
				chest_minecart = true
				fox = true
				spider = true
				skeleton = true
				bat = true
				glow_squid = true
				zombie = true
				creeper = true
				enderman = true
				sheep = true
				slime = true
				zombie_villager = true
				chicken = true
				villager = true
				pillager = true
				cow = true
				witch = true
				painting = true
				axolotl = true
				strider = true
				zombified_piglin = true
				piglin = true
				ghast = true
				magma_cube = true
				piglin_brute = true
				item_frame = true
				blaze = true
				wither_skeleton = true
				arrow = true
				experience_orb = true
				rabbit = true
				minecart = true
				squid = true
				vindicator = true
				armor_stand = true
				iron_golem = true
				ravager = true
				evoker = true
				wolf = true
				pig = true
				tropical_fish = true
				pufferfish = true
				drowned = true
				cod = true
				guardian = true
				dolphin = true
				ocelot = true
				cat = true
				parrot = true
				hoglin = true
				allay = true
				lightning_bolt = true
				frog = true
				wandering_trader = true
				trader_llama = true
				phantom = true
				potion = true
				llama = true
				stray = true
				experience_bottle = true
				zombie_horse = true
				skeleton_horse = true
				egg = true
				panda = true
				turtle = true
				polar_bear = true
				horse = true
				silverfish = true
				salmon = true
				goat = true
				ender_pearl = true
				warden = true
				husk = true
				area_effect_cloud = true
				llama_spit = true
				evoker_fangs = true
				snow_golem = true
				cave_spider = true
				elder_guardian = true
				illusioner = true
				tnt_minecart = true
				glow_item_frame = true
				hopper_minecart = true
				leash_knot = true
				camel = true
				firework_rocket = true
				donkey = true
				ender_dragon = true
				shulker = true
				shulker_bullet = true
				small_fireball = true
				mule = true
				eye_of_ender = true
				endermite = true
				snowball = true
				boat = true
				zoglin = true
				vex = true

			[light_sources.settings.entities.irons_spellbooks]
				necromancer = true
				blood_needle = true
				magic_missile = true
				dead_king_corpse = true
				archevoker = true
				pyromancer = true
				priest = true
				icicle = true
				summoned_zombie = true
				summoned_skeleton = true
				cryomancer = true

			[light_sources.settings.entities.wan_ancient_beasts]
				toxlacanth = true
				paleontologist = true
				eater = true
				walker = true
				crusher = true
				glider = true
				soarer = true

			[light_sources.settings.entities.royalvariations]
				royal_zombie = true
				royal_creeper = true
				royal_skeleton = true
				projectile_marked_arrow = true
				projectile_royal_bomb_projectile = true

			[light_sources.settings.entities.naturalist]
				snake = true
				boar = true
				snail = true
				cardinal = true
				firefly = true
				robin = true
				coral_snake = true
				lizard = true
				butterfly = true
				sparrow = true
				bluejay = true
				canary = true
				vulture = true
				bear = true
				tortoise = true
				deer = true
				finch = true
				elephant = true
				duck = true
				alligator = true
				bass = true
				lion = true
				rhino = true
				hippo = true
				giraffe = true
				lizard_tail = true
				zebra = true
				dragonfly = true
				duck_egg = true
				catfish = true

			[light_sources.settings.entities.alshanex_familiars]
				summoner_pet = true
				necromancer_pet = true
				scorcher_pet = true
				default_note = true
				black_note = true
				hunter_pet = true
				druid_pet = true
				mage_pet = true
				harp_explosion = true

			[light_sources.settings.entities.tameablebeasts]
				tameable_racoon = true
				argentavis = true
				crested_gecko = true
				tameable_chikote = true
				giant_grasshopper = true
				tameable_beetle = true
				ground_beetle = true
				giant_roly_poly = true
				tameable_penguin = true
				quetzalcoatlus = true
				graptera = true

			[light_sources.settings.entities.burnt]
				smoke = true
				volcano = true
				geyser = true
				falling_slab = true
				wisp = true
				burnt_forest_spawner = true
				soul_spawner = true

			[light_sources.settings.entities.tide]
				pike = true
				mint_carp = true
				catfish = true
				trout = true
				bass = true
				yellow_perch = true
				bluegill = true
				guppy = true
				mackerel = true
				tuna = true
				sailfish = true
				barracuda = true
				angelfish = true
				ocean_perch = true
				clayfish = true
				fishing_bobber = true
				anglerfish = true
				glowfish = true
				cave_eel = true
				iron_tetra = true
				crystal_shrimp = true
				cave_crawler = true
				lapis_lanternfish = true
				gilded_minnow = true
				deep_grouper = true
				carp = true
				red_snapper = true
				brook_trout = true
				rainbow_trout = true
				flounder = true
				anchovy = true
				mahi_mahi = true
				great_white_shark = true
				slimy_salmon = true
				crystalline_carp = true
				shadow_snapper = true
				swordfish = true
				abyss_angler = true
				luminescent_jellyfish = true
				bedrock_tetra = true
				smallmouth_bass = true
				snook = true
				largemouth_bass = true
				manta_ray = true
				white_crappie = true
				black_crappie = true
				inferno_guppy = true
				ember_koi = true
				ash_perch = true
				warped_guppy = true
				soulscale = true
				magma_mackerel = true
				witherfin = true
				obsidian_pike = true
				volcano_tuna = true

			[light_sources.settings.entities.swem]
				swem_horse = true

			[light_sources.settings.entities.enigmaticgraves]
				grave = true

			[light_sources.settings.entities.just_in_nether]
				bullkin_brute = true
				bullkin = true
				pigmar = true
				zombiefied_bullkin = true
				dullkin = true
				bullkindar = true

			[light_sources.settings.entities.psychedelicraft]
				reality_rift = true

			[light_sources.settings.entities.bloomingnature]
				termite = true
				wandering_gardener = true

			[light_sources.settings.entities.horse_colors]
				horse_felinoid = true
				donkey = true

			[light_sources.settings.entities.furnish]
				seat = true

			[light_sources.settings.entities.breezy]
				hot_air_balloon = true

			[light_sources.settings.entities.spelunkery]
				dust_bunny = true

			[light_sources.settings.entities.variantsandventures]
				gelid = true
				murk = true
				verdant = true
				thicket = true

			[light_sources.settings.entities.zombifiedplayer]
				zombified_player = true

			[light_sources.settings.entities.enhancedai]
				thrown_web = true
				fishing_hook = true

			[light_sources.settings.entities.astikorcarts]
				supply_cart = true
				plow = true
				animal_cart = true
				postilion = true

			[light_sources.settings.entities.miapi]
				thrown_item = true

			[light_sources.settings.entities.immersive_furniture]
				sitting = true

			[light_sources.settings.entities.goodending]
				woodpecker = true
				marsh = true

			[light_sources.settings.entities.create_bic_bit]
				herring = true

			[light_sources.settings.entities.goety]
				heretic = true
				wraith = true
				web_spider = true
				warlock = true
				maverick = true
				reaper = true
				obsidian_monolith = true
				muck_wraith = true
				icy_spider = true
				haunted_armor = true
				bone_spider = true
				cairn_necromancer = true
				ice_bouquet = true
				web_shot = true
				spider_web = true
				black_wolf = true
				scatter_mine = true
				blaze_servant = true
				fire_pillar = true
				crusher = true
				storm_caster = true
				necromancer = true
				ill_bomb = true
				wartling = true
				cryologer = true
				snap_fungus = true
				wraith_servant = true
				zombie_servant = true
				falling_block = true
				fang = true
				doppelganger = true
				fireball = true
				reaper_servant = true
				magic_ground = true
				rain_arrow = true
				vanguard_servant = true
				phantom_servant = true
				skeleton_pillager = true
				zombie_vindicator = true
				blackguard_servant = true
				haunted_skull = true
				totemic_wall = true
				earth_fist = true
				hail_cloud = true
				ice_chunk = true
				ice_spike = true
				poison_quill = true
				blossom_ball = true
				blossom_thorn = true
				vine_hook = true
				bear_servant = true
				slime_servant = true
				quick_growing_vine = true
				ice_storm = true
				leapleaf = true
				whisperer = true
				entangle_vines = true
				cushion = true
				updraft_blast = true
				razor_wind = true
				monsoon_cloud = true
				electro_orb = true
				trident_storm = true
				bouncy_bubble = true
				guardian_servant = true
				biomine = true
				acid_pool = true
				tidal_surge = true
				lavaball = true
				magma_bomb = true
				magma_cube_servant = true
				mini_ghast = true
				wither_skull = true
				summon_circle_boss = true
				endersent = true
				camera_shake = true
				ender_keeper = true
				hell_chant = true
				fire_blast_trap = true
				zpiglin_servant = true
				trampler = true
				crypt_slime = true
				tropical_slime_servant = true
				hostile_black_wolf = true

			[light_sources.settings.entities.cataclysm]
				void_vortex = true
				deepling_angler = true
				deepling = true
				deepling_brute = true
				deepling_priest = true
				coralssus = true
				deepling_warlock = true
				lionfish = true
				the_harbinger = true
				the_watcher = true
				the_prowler = true
				ender_golem = true
				hippocamtus = true
				the_baby_leviathan = true
				the_leviathan = true
				ancient_remnant = true
				ignis = true
				koboleton = true

			[light_sources.settings.entities.tconstruct]
				sky_slime = true
				fluid_spit = true
				indestructible_item = true
				ender_slime = true
				terracube = true
				thrown_tool = true

			[light_sources.settings.entities.furniture]
				chair = true
				pells = true
				canvas = true

			[light_sources.settings.entities.unusual_furniture]
				sit = true
				sit_stools = true

			[light_sources.settings.entities.redeco]
				seat = true

			[light_sources.settings.entities.alekiships]
				cannonball = true
				vehicle_part = true
				vehicle_cleat = true
				compartment_empty = true
				vehicle_switch_windlass = true
				vehicle_anchor = true
				vehicle_mast = true
				vehicle_switch_sail = true
				vehicle_collider = true

				[light_sources.settings.entities.alekiships.rowboat]
					birch = true

				[light_sources.settings.entities.alekiships.sloop]
					oak = true

			[light_sources.settings.entities.create]
				stationary_contraption = true

			[light_sources.settings.entities.pyrellium]
				bomb_flower = true

			[light_sources.settings.entities.tfmg]
				spark = true
				pipe_bomb = true
				lithium_spark = true
				thermite_grenade = true
				zinc_grenade = true
				copper_grenade = true
				blue_spark = true

			[light_sources.settings.entities.iguanatweaksreborn]
				quartz_arrow = true

			[light_sources.settings.entities.betterend]
				shadow_walker = true
				dragonfly = true
				cubozoa = true
				end_fish = true
				end_slime = true
				silk_moth = true

			[light_sources.settings.entities.tinker_transplant]
				tinker_shuriken = true

			[light_sources.settings.entities.snowyspirit]
				sled = true
				gingerbread_golem = true
				container_entity = true

			[light_sources.settings.entities.xenotech]
				dummy = true

			[light_sources.settings.entities.simpleplanes]
				cargo_plane = true
				plane = true
				helicopter = true

			[light_sources.settings.entities.valkyrienskies]
				ship_mounting_entity = true

			[light_sources.settings.entities.stdrive]
				apocalypse_car = true

			[light_sources.settings.entities.biomeswevegone]
				wreath = true
				pumpkin_warden = true

			[light_sources.settings.entities.trackwork]
				wheel_entity = true

			[light_sources.settings.entities.call_of_yucutan]
				dart = true
				mitnal_monkey = true

			[light_sources.settings.entities.car]
				car = true

			[light_sources.settings.entities.adpother]
				gas = true

			[light_sources.settings.entities.unusualend]
				undead_enderling = true
				ender_blob = true
				enderbulb = true
				small_enderbulb = true
				ender_firefly = true
				block_updater = true
				dragling = true
				bolok = true
				glub = true
				bluk = true
				spunkler = true
				wandering_pearl_projectile = true
				shiny_grenade_projectile = true
				leeching_charge_projectile = true

			[light_sources.settings.entities.endergetic]
				puff_bug = true
				booflo = true
				booflo_baby = true
				booflo_adolescent = true
				poise_cluster = true

			[light_sources.settings.entities.crockpot]
				volt_goat = true

			[light_sources.settings.entities.natures_spirit]
				ns_boat = true

			[light_sources.settings.entities.botania]
				mana_burst = true

			[light_sources.settings.entities.projecte]
				lens_projectile = true
				lava_projectile = true
				homing_arrow = true

			[light_sources.settings.entities.faunify]
				rolypoly = true
				fennec = true
				silkmoth = true
				weevil = true
				leafsheep = true
				weasel = true
				hedgehog = true
				chinchilla = true
				ringtailcat = true
				opossum = true
				mouse = true
				beetle = true

			[light_sources.settings.entities.beansbackpacks]
				backpack = true
				winged_backpack = true

